# Generated by Django 5.2.6 on 2025-10-14 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_platenumber',
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('black', 'Black'), ('silver', 'Silver'), ('white', 'White'), ('bronze', 'Bronze')], default='black', max_length=20),
        ),
    ]
