# Generated by Django 5.2.6 on 2025-10-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_user_remove_user_user_platenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_platenumber',
            field=models.IntegerField(blank=True, default='0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
    ]
