# Generated by Django 5.2.6 on 2025-10-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_car_platenumber_alter_user_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The primary owner of this car.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.user'),
        ),
        migrations.AddField(
            model_name='car',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users this car is shared with.', related_name='shared_cars', to='main.user'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_platenumber',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BorrowedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from', models.DateField()),
                ('borrowed_until', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='borrowers',
            field=models.ManyToManyField(blank=True, help_text='Users who have borrowed this car.', related_name='borrowed_cars', through='main.BorrowedCar', to='main.user'),
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(help_text='The user who bought the car.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_cars', to='main.user')),
                ('car', models.OneToOneField(help_text='The car associated with this purchase record.', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_info', to='main.car')),
            ],
        ),
    ]
