# Generated by Django 5.2.6 on 2025-10-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_car_car_owner_car_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='shared_with_users', to='main.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The primary owner of this car.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cars', to='main.user'),
        ),
    ]
