# Generated by Django 5.2.6 on 2025-10-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_cars_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='borrowers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cars',
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('owner', 'Owner'), ('shared', 'Shared'), ('borrowed', 'Borrowed')], default='owner', max_length=20)),
                ('date_acquired', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Users who own or share this car.', related_name='owned_cars', through='main.CarOwnership', to='main.user'),
        ),
        migrations.DeleteModel(
            name='BorrowedCar',
        ),
    ]
