# Generated by Django 5.2.6 on 2025-10-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_car_borrowers_remove_car_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('user', 'Regular User')], default='user', max_length=20),
        ),
    ]
